config/routes.rb
Rails.application.routes.draw do
  root "logins#show"

  resource :login, only: [:show, :create, :destroy]
  resource :dashboard, only: :show
  resource :list, only: [:show, :create]

  get 'logout', to: 'logins#destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  has_many :list_elements, dependent: :destroy
  has_many :list_users, dependent: :destroy
  has_many :users, through: :list_users
end

app/models/list_element.rb
class ListElement < ApplicationRecord
  belongs_to :list
end

app/models/list_user.rb
class ListUser < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/models/session.rb
class Session
  def initialize(user)
    @user = user
  end

  def cookie
    { value: token, expires: 1.month.from_now, http_only: true }
  end

  def token
    SessionToken.new(@user).generate
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :list_users, dependent: :destroy
  has_many :lists, through: :list_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ResponseError do
    action
  end

  private

  def action
    redirect_to login_path
  end

  def submit_form(form)
    if form.validate(params.to_unsafe_hash)
      form.save
      redirect_to form.model
    else
      flash.now[:alert] = form.errors.to_a.join(', ')
      render action: 'create', status: :bad_request
    end
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_user

  attr_reader :current_user

  private

  def authenticate_user
    @current_user = VerifyToken.new(cookies[:session_cookie], :session).call
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < BaseController
  def show; end
end

app/controllers/lists_controller.rb
class ListsController < BaseController
  def show
    @list = List.find(params[:format])
  end

  def create
    submit_form(ListForm.new(current_user.lists.create))
  end
end

app/controllers/logins_controller.rb
class LoginsController < BaseController
  skip_before_action :authenticate_user, only: :create

  def show
    redirect_to dashboard_path if @current_user.present?
  end

  def create
    @session = create_session

    return unless @session.present?

    cookies[:session_cookie] = @session.cookie
    redirect_to dashboard_path
  end

  def destroy
    cookies.delete('session_cookie')
    flash[:notice] = 'You have successfully logged out.'
    redirect_to login_url
  end

  private

  def create_session
    @session ||= CreateSession.new(params[:email], params[:password]).call
  end

  def action
    flash.now[:alert] = 'Incorrect email or password. Please try again.'
    render action: 'show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/base/_list_form.html.erb
<h5>Create list:</h5>
<%= form_with local: true, url: list_path, action: :create do |f| %>
  <%= f.text_field(:name, placeholder: "List name", required: true) %>
  <%= f.text_field(:description, placeholder: "Description") %>
  <%= f.submit("Create") %>
<% end %>

app/views/dashboards/show.html.erb
<%= render partial: "list_form" %>

app/views/layouts/_header.html.erb
<%= link_to 'Log out', logout_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommonBond</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <% unless params[:controller] == 'logins' %>
      <%= render 'layouts/header' %>
    <% end %>
    <% flash.each do |type, msg| %>
        <div class="alert flash-<%= type %>">
          <%= msg %>
        </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<%= render partial: "list_form" %>

app/views/lists/show.html.erb
<p>
<% @list.tap do |list| %>
  <%= list.name %>
  <%= list.description %>
  <% end %>
</p>

app/views/logins/show.html.erb
<%= form_with local: true, url: login_path, action: :create do |f| %>
  <%= f.email_field(:email, placeholder: "Email", required: true) %>
  <%= f.password_field(:password, placeholder: "Password", required: true) %>
  <%= f.submit("LOG IN") %>
<% end %>